### ISSUE TITLE
Problem with "PaymentSourceApplePay" token

### ISSUE THREAD

**Issue by AlexMelikhov** [Centrobill/php-sdk-v1#11]
Hello! I’ve encountered an issue with the token for PaymentSourceApplePay. It exceeds the maximum allowed token size (512), and as far as I know, the new API requires an array to be passed.

I’ve updated PaymentSourceApplePay accordingly, added ApplePayPayload, and also updated your tests:

`<?php

namespace Centrobill\Sdk\ValueObject;

use Centrobill\Sdk\Exception\TokenException;

final class ApplePayPayload
{
    private array $payload;

    public function __construct(array $payload)
    {
        $this->payload = $payload;
    }

    public static function fromToken(string $token): ApplePayPayload
    {
        return new self(json_decode($token, true));
    }

    /**
     * @throws TokenException
     */
    protected function checkValue($value)
    {
        if (empty($value)) {
            throw TokenException::emptyValue();
        }
    }

    public function getPayload(): array
    {
        return $this->payload;
    }
}
`

`<?php

namespace Centrobill\Sdk\Entity\PaymentSource;

use Centrobill\Sdk\ValueObject\ApplePayPayload;
use Centrobill\Sdk\ValueObject\EmulateCode;
use Centrobill\Sdk\ValueObject\PaymentSourceType;

class PaymentSourceApplePay extends AbstractPaymentSource
{
    /**
     * @var ApplePayPayload $payload
     */
    private ApplePayPayload $payload;

    /**
     * @var ?EmulateCode $emulateCode
     */
    private ?EmulateCode $emulateCode;

    public function __construct(ApplePayPayload $payload, ?EmulateCode $emulateCode = null)
    {
        $this->payload = $payload;
        $this->emulateCode = $emulateCode;
    }

    public function setEmulateCode(EmulateCode $emulateCode): self
    {
        $this->emulateCode = $emulateCode;
        return $this;
    }

    public function toArray(): array
    {
        $data = [
            'type' => PaymentSourceType::PAYMENT_SOURCE_APPLEPAY,
            'token' => $this->payload->getPayload(),
        ];

        if ($this->emulateCode !== null) {
            $data['emulateCode'] = (string)$this->emulateCode;
        }

        return array_merge($data, parent::toArray());
    }
}
`

And test:

`<?php

namespace Tests\Centrobill\Sdk\Entity\PaymentSource;

use Centrobill\Sdk\Entity\PaymentSource\PaymentSourceApplePay;
use Centrobill\Sdk\ValueObject\ApplePayPayload;
use Centrobill\Sdk\ValueObject\EmulateCode;
use Centrobill\Sdk\ValueObject\Mid;
use Centrobill\Sdk\ValueObject\PaymentSourceType;
use Centrobill\Sdk\ValueObject\Token;
use PHPUnit\Framework\TestCase;

class PaymentSourceApplePayTest extends TestCase
{
    private PaymentSourceApplePay $paymentSource;

    private static array $payload = ['test' => 'test'];

    public function testConstruct()
    {
        $this->createEntity();
        self::assertInstanceOf(PaymentSourceApplePay::class, $this->paymentSource);
    }

    public function testToArrayWithoutMid()
    {
        $this->createEntity();
        self::assertEquals([
            'type' => PaymentSourceType::PAYMENT_SOURCE_APPLEPAY,
            'emulateCode' => '1234',
            'token' => self::$payload,
        ], $this->paymentSource->toArray());
    }

    public function testToArrayWithMid()
    {
        $this->createEntity();
        $this->paymentSource->setMid(new Mid('MidTest'));
        self::assertEquals([
            'type' => PaymentSourceType::PAYMENT_SOURCE_APPLEPAY,
            'emulateCode' => '1234',
            'token' => self::$payload,
            'mid' => 'MidTest',
        ], $this->paymentSource->toArray());
    }

    private function createEntity()
    {
        $this->paymentSource = new PaymentSourceApplePay(
            ApplePayPayload::fromToken(json_encode(self::$payload)),
            new EmulateCode('1234')
        );
    }
}
`

also in composer.json:

`"require": {
...,
"ext-json": "*"
}`

It would be great if you could include this in the release! :)

**Comment by aiavorskii** [comment]
Hi @AlexMelikhov! Thanks for reporting that problem. We've updated code in 1.1.1 version
