### ISSUE TITLE
Undefined property: stdClass::$expiredAt

### ISSUE THREAD

**Issue by websolutionfalcon** [Centrobill/php-sdk-v1#2]
Hi there!
I am trying to run generateCardDataToken.
And right now you are relaying on expiredAt property in `GenerateCardDataTokenResponse`:
```
public function getExpiredAt()
    {
        return $this->data->expiredAt;
    }
```
But actual property is expireAt not expire**d**At

```
Centrobill\Sdk\Http\Response\GenerateCardDataTokenResponse {
  #data: {#1525 ▼
    +"token": "0db634ec-fee0-46fe-bc16-c8c9aa2354dc"
    +"expireAt": 1722437420
  }
}
```

**Comment by aiavorskii** [comment]
We've updated `GenerateCardDataTokenResponse`

I you have any problems getting any response property you can also use `getData` array, which returns raw response data

**Comment by websolutionfalcon** [comment]
@aiavorskii Thanks, it fixed now!
